apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    config.json: AgBIzwvlJ8864DhdCz+x/7f0eN1SmOCgkkG6CzNIwAGNmdadj68AVBj/iqYNn4qc12+pNybyoRQMe6zOSmyEZkHsf7Koh+H7UB7PNUblb5j9fcWKIw8wVe/FW7RghC+c4aA/T7KefTIv5NeFWci/D+Dx+1U6l9i7P3/3cBFqm23JU4s6n06yBlTOru9IwmEsWMWtwDsgkVjf51sgAOWTCJOLLRHYE+qcV+vcWy48Mxqh14P4eGXr76HPzZmW0nUCxl3pQCJcyUe2rD6x2xRh0vzXzzemAzv7B3RWzKxEKhHt8RlC0zvaFT0M9RjMIJ7JanIN6OhkGWzXsnLogMiWs2sGoADB/nZmAVcdApGfspKetZRO5P781A82g9udu8IgugwYRm9D129RJWG6zGyqFN6MwiPBPaquD4ifbF0fjn7f4qZM7l6dwgTY2HgEhjowAvpP4sA3xv8YTg083gejtQBVmE26pvM4CiLN1DQgJvxn2q74fAKIDZMyu5NUfHo4nq3jwcVXeHcRJZab5EFy9z9jRfKCMMxFhFv6DDD3iOJ+zUJDj5lnDBu01WoNjD0GaZco9fdt6T1NFRKHGQj7ml+zLjJehTEKOMGiUuayvvs/oy/GHYQumUNzik0yn3OzVRre7qc1r5sgWGD6yY431VMxbMGN32n2yMOFhZngjdLsxMwuCEslnA/YsJvH22W/2GDxJFrMUWnlN+XvqChWospjzJK50XBxsW3AhLmD/pZCfOYWBKIJZhbHYZ8ma/WehEr+5Do7WVPKLZ6X/pIp7vlz6HgPLwx5b1KEK7A0bTkkdkqBAxkIfMK5sDP5CDMO7eXeGejNjOBujR5w33nLH1xrBiLRaF4ak3LO+CVpYKH+PBI+cA==
  template:
    metadata:
      creationTimestamp: null
      name: docker-config
      namespace: build-pipelines