apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: {{ .Release.Namespace }}
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1-s3-artifact-repository
data:
  default-v1-s3-artifact-repository: |
    archiveLogs: false
    s3:
      accessKeySecret:
        key: access-key
        name: aws-s3-normans-artifactory
      bucket: normans-artifactory
      endpoint: s3.ap-southeast-1.amazonaws.com
      insecure: false
      secretKeySecret:
        key: secret-key
        name: aws-s3-normans-artifactory