apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-executor
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: argo-workflows-admin
  apiGroup: rbac.authorization.k8s.io